# -*- coding: utf-8 -*-
"""Proyecto_visualizcion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmOKt_jTmCKepjhbQBUdHmtzULLTXqB_
"""

import os
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# =====================================================
# CONFIGURACIÓN
# =====================================================

FICHERO = "merged_countries_fin.xlsx"
CARPETA = "figuras"

os.makedirs(CARPETA, exist_ok=True)

# =====================================================
# CARGA DEL DATASET
# =====================================================

df = pd.read_excel(FICHERO)

df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_", regex=False)
    .str.replace("/", "_", regex=False)
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace("%", "Pct", regex=False)
)

print("Columnas cargadas:")
print(df.columns.tolist())

# =====================================================
# CONVERSIÓN NUMÉRICA
# =====================================================

numeric_cols = [
    'AML_Score', 'CPI_Score', 'Ranking_Corruption',
    'Minimum_Score', 'Maximum_Score', 'IFS_Score',
    'Ranking_HDI', 'GDP', 'GDP_per_capita',
    'Infant_Mortality', 'Population_Density_pp_km2',
    'Unemployment_Pct', 'Population_Growth',
    'Birth_Rate', 'Death_Rate', 'Life_Expectancy',
    'Electric_Consumption_kWh_pp',
    'Internet_Usage_Pct',
    'ADB', 'AfDB', 'EIU', 'FH', 'GI',
    'IMD', 'PERC', 'PRS', 'TI',
    'VDP', 'WB', 'WEF', 'WJP'
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )

# =====================================================
# AÑO DE ANÁLISIS
# =====================================================

YEAR = 2018

df_year = df[df["Year"] == YEAR].copy()

print("\nPaíses analizados:", len(df_year))

# =====================================================
# IMPUTACIÓN SIMPLE
# =====================================================

for col in numeric_cols:

    if col in df_year.columns:

        mediana = df_year[col].median()

        df_year[col] = df_year[col].fillna(
            mediana
        )

# =====================================================
# FUNCIÓN GUARDAR
# =====================================================

def guardar(fig, nombre):

    fig.show()

    fig.write_html(
        os.path.join(
            CARPETA,
            f"{nombre}.html"
        )
    )

    print(f"Guardado: {nombre}")

# =====================================================
# 1 MAPA AML
# =====================================================

fig = px.choropleth(
    df_year,
    locations="ISO3",
    color="AML_Score",
    hover_name="Country_Name",
    color_continuous_scale="Reds",
    title="¿Dónde se concentra el riesgo AML?"
)

guardar(fig, "01_mapa_aml")

# =====================================================
# 2 TOP 20 AML
# =====================================================

top20 = (
    df_year
    .sort_values("AML_Score", ascending=False)
    .head(20)
)

fig = px.bar(
    top20,
    x="AML_Score",
    y="Country_Name",
    orientation="h",
    color="AML_Score",
    color_continuous_scale="Reds",
    text="AML_Score",
    title="Los países con mayor riesgo AML"
)

fig.update_layout(height=800)

guardar(fig, "02_top20")

# =====================================================
# 3 PIB VS AML
# =====================================================

fig = px.scatter(
    df_year,
    x="GDP_per_capita",
    y="AML_Score",
    color="Income_Group",
    size="GDP",
    hover_name="Country_Name",
    trendline="ols",
    log_x=True,
    title="¿La riqueza reduce el riesgo AML?"
)

guardar(fig, "03_gdp_vs_aml")

# =====================================================
# 4 Corrupción
# =====================================================

fig = px.scatter(
    df_year,
    x="CPI_Score",
    y="AML_Score",
    color="Region_Name",
    hover_name="Country_Name",
    title="Corrupción percibida y riesgo AML"
)

guardar(fig, "04_corrupcion")

# =====================================================
# 5 INCOME GROUP
# =====================================================

fig = px.box(
    df_year,
    x="Income_Group",
    y="AML_Score",
    color="Income_Group",
    title="AML según nivel de ingresos"
)

guardar(fig, "05_income")

# =====================================================
# 6 REGIONES
# =====================================================

fig = px.violin(
    df_year,
    x="Region_Name",
    y="AML_Score",
    box=True,
    color="Region_Name",
    title="Distribución regional del riesgo AML"
)

guardar(fig, "06_region")

# =====================================================
# 7 EVOLUCIÓN
# =====================================================
trend = (
    df.groupby(
        ["Year","Region_Name"]
    )["AML_Score"]
    .mean()
    .reset_index()
)

fig = px.line(
    trend,
    x="Year",
    y="AML_Score",
    color="Region_Name",
    markers=True,
    title="Evolución temporal del riesgo AML"
)

guardar(fig, "07_evolucion")

# =====================================================
# 8 MATRIZ CORRELACIONES
# =====================================================

corr_vars = [
    "AML_Score",
    "CPI_Score",
    "GDP_per_capita",
    "Internet_Usage_Pct",
    "Unemployment_Pct"
]

corr = df_year[corr_vars].corr()

fig = px.imshow(
    corr.round(2),
    text_auto=True,
    color_continuous_scale="RdBu_r",
    zmin=-1,
    zmax=1,
    title="Matriz de correlaciones"
)

guardar(fig, "08_correlaciones")

# =====================================================
# 9 FACTORES MÁS ASOCIADOS
# =====================================================

factor_vars = [
    "CPI_Score",
    "GDP_per_capita",
    "Internet_Usage_Pct",
    "Unemployment_Pct",
    "Population_Growth",
    "Birth_Rate",
    "Death_Rate"
]

corrs = []

for var in factor_vars:

    if var in df_year.columns:

        temp = df_year[
            ["AML_Score", var]
        ].dropna()

        if len(temp) > 10:

            r = temp.corr().iloc[0,1]

            corrs.append({
                "Variable": var,
                "Correlacion": r,
                "Abs": abs(r)
            })

corr_df = pd.DataFrame(corrs)

corr_df = corr_df.sort_values("Abs")

fig = px.bar(
    corr_df,
    x="Abs",
    y="Variable",
    orientation="h",
    color="Correlacion",
    color_continuous_scale="RdBu_r",
    text=corr_df["Correlacion"].round(2),
    title="¿Qué factores están más asociados al AML?"
)

guardar(fig, "09_factores_asociados_aml")

# =====================================================
# 10 CORRUPCIÓN VS AML CON REGRESIÓN
# =====================================================

fig = px.scatter(
    df_year,
    x="CPI_Score",
    y="AML_Score",
    color="Region_Name",
    hover_name="Country_Name",
    trendline="ols",
    title="La calidad institucional y el riesgo AML"
)

guardar(fig, "10_corrupcion_vs_aml")

# =====================================================
# 11 PCA + KMEANS
# =====================================================

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

cluster_vars_for_scaling = [
    col for col in numeric_cols
    if col in df_year.columns
]

data = df_year[cluster_vars_for_scaling].copy()

# Convertir a numérico
for col in data.columns:
    data[col] = pd.to_numeric(
        data[col],
        errors="coerce"
    )

# Eliminar columnas totalmente vacías
data = data.dropna(axis=1, how="all")

# Eliminar columnas constantes
data = data.loc[
    :,
    data.nunique(dropna=True) > 1
]

# Imputar medianas
for col in data.columns:

    med = data[col].median()

    if not np.isnan(med):
        data[col] = data[col].fillna(med)

# Eliminar filas que sigan teniendo NaN
data = data.dropna()

print("Variables utilizadas:")
print(data.columns.tolist())

print("\nNaN restantes:")
print(data.isna().sum().sum())

# Escalado
X = StandardScaler().fit_transform(data)

print("\nNaN en X:", np.isnan(X).sum())

# Clustering
kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X)

# PCA
coords = PCA(
    n_components=2
).fit_transform(X)

# IMPORTANTE:
plot_df = df_year.loc[data.index].copy()

plot_df["PCA1"] = coords[:, 0]
plot_df["PCA2"] = coords[:, 1]
plot_df["Cluster"] = clusters.astype(str)

fig = px.scatter(
    plot_df,
    x="PCA1",
    y="PCA2",
    color="Cluster",
    hover_name="Country_Name",
    hover_data=[
        "Region_Name",
        "Income_Group"
    ],
    title="Perfiles de países según riesgo, economía e instituciones"
)

fig.update_layout(
    width=1000,
    height=700
)

guardar(fig, "11_pca_kmeans_perfiles")

# =====================================================
# 12 PERFIL DE CLUSTERS
# =====================================================

cluster_profile = (
    plot_df
    .groupby("Cluster")
    .agg({
        "AML_Score":"mean",
        "CPI_Score":"mean",
        "GDP_per_capita":"mean"
    })
    .reset_index()
)

fig = px.bar(
    cluster_profile,
    x="Cluster",
    y=[
        "AML_Score",
        "CPI_Score"
    ],
    barmode="group",
    title="Perfil medio de los clusters identificados"
)

guardar(fig, "12_perfil_clusters")

# =====================================================
# 13 RANKING REGIONAL
# =====================================================

region_mean = (
    df_year
    .groupby("Region_Name")["AML_Score"]
    .mean()
    .sort_values()
    .reset_index()
)

fig = px.bar(
    region_mean,
    x="AML_Score",
    y="Region_Name",
    orientation="h",
    color="AML_Score",
    color_continuous_scale="Reds",
    title="Comparación regional del riesgo AML"
)

guardar(fig, "13_ranking_regional")

# =====================================================
# 14 INTERNET VS AML
# =====================================================

df_net = df_year.dropna(
    subset=[
        "Internet_Usage_Pct",
        "AML_Score"
    ]
)

fig = px.scatter(
    df_net,
    x="Internet_Usage_Pct",
    y="AML_Score",
    color="Income_Group",
    hover_name="Country_Name",
    hover_data=[
        "Region_Name",
        "CPI_Score",
        "GDP_per_capita"
    ],
    trendline="ols",
    title="Digitalización y riesgo AML"
)

fig.update_layout(
    xaxis_title="Uso de Internet (%)",
    yaxis_title="AML Score",
    legend_title="Grupo de ingresos",
    width=1000,
    height=700
)

guardar(fig, "14_internet_vs_aml")

# =====================================================
# 15 MAPA MUNDIAL DE CLUSTERS
# =====================================================

cluster_map = plot_df.copy()

cluster_names = {
    "0": "Cluster 0",
    "1": "Cluster 1",
    "2": "Cluster 2",
    "3": "Cluster 3"
}

cluster_map["Cluster_Name"] = (
    cluster_map["Cluster"]
    .astype(str)
    .map(cluster_names)
)

fig = px.choropleth(
    cluster_map,
    locations="ISO3",
    color="Cluster",
    hover_name="Country_Name",
    hover_data=[
        "AML_Score",
        "CPI_Score",
        "Income_Group"
    ],
    title="Distribución mundial de los perfiles de países",
    color_discrete_map={
        "0": "#1f77b4",
        "1": "#ff7f0e",
        "2": "#2ca02c",
        "3": "#d62728"
    }
)

fig.update_layout(
    width=1200,
    height=700
)

guardar(fig, "15_mapa_clusters")