# -*- coding: utf-8 -*-
"""Visualizacion_luis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wU46r7Jl1GJ3oImGnsn6ytydGRykQwa4
"""

import os
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# =====================================================
# CONFIGURACIÓN
# =====================================================

FICHERO = "merged_countries_fin.xlsx"
CARPETA = "figuras"

os.makedirs(CARPETA, exist_ok=True)

# =====================================================
# CARGA DEL DATASET
# =====================================================

df = pd.read_excel(FICHERO)

df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_", regex=False)
    .str.replace("/", "_", regex=False)
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace("%", "Pct", regex=False)
)

print("Columnas cargadas:")
print(df.columns.tolist())

# =====================================================
# CONVERSIÓN NUMÉRICA
# =====================================================

numeric_cols = [
    'AML_Score', 'CPI_Score', 'Ranking_Corruption',
    'Minimum_Score', 'Maximum_Score', 'IFS_Score',
    'Ranking_HDI', 'GDP', 'GDP_per_capita',
    'Infant_Mortality', 'Population_Density_pp_km2',
    'Unemployment_Pct', 'Population_Growth',
    'Birth_Rate', 'Death_Rate', 'Life_Expectancy',
    'Electric_Consumption_kWh_pp',
    'Internet_Usage_Pct',
    'ADB', 'AfDB', 'EIU', 'FH', 'GI',
    'IMD', 'PERC', 'PRS', 'TI',
    'VDP', 'WB', 'WEF', 'WJP'
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )

# =====================================================
# AÑO DE ANÁLISIS
# =====================================================

YEAR = 2018

df_year = df[df["Year"] == YEAR].copy()

print("\nPaíses analizados:", len(df_year))

# =====================================================
# IMPUTACIÓN SIMPLE
# =====================================================

for col in numeric_cols:

    if col in df_year.columns:

        mediana = df_year[col].median()

        df_year[col] = df_year[col].fillna(
            mediana
        )

# =====================================================
# FUNCIÓN GUARDAR
# =====================================================

def guardar(fig, nombre):

    fig.show()

    fig.write_html(
        os.path.join(
            CARPETA,
            f"{nombre}.html"
        )
    )

    print(f"Guardado: {nombre}")

print(df.groupby("Year")["GDP_per_capita"].count())

# =====================================================
# 1 MAPA AML
# =====================================================

if {"ISO3", "AML_Score"}.issubset(df_year.columns):

    fig = px.choropleth(
        df_year,
        locations="ISO3",
        color="AML_Score",
        hover_name="Country_Name",
        color_continuous_scale="Reds",
        title=f"AML Score ({YEAR})"
    )

    guardar(fig, "01_mapa_aml")

# =====================================================
# 2 TOP 20 AML
# =====================================================

if "AML_Score" in df_year.columns:

    top20 = (
        df_year
        .sort_values("AML_Score", ascending=False)
        .head(20)
    )

    fig = px.bar(
        top20,
        x="AML_Score",
        y="Country_Name",
        orientation="h",
        color="AML_Score",
        title="Top 20 AML Score"
    )

    guardar(fig, "02_top20")

# =====================================================
# 3 GDP vs AML
# =====================================================

df_gdp = df_year.dropna(
    subset=[
        "GDP_per_capita",
        "AML_Score"
    ]
)

fig = px.scatter(
    df_gdp,
    x="GDP_per_capita",
    y="AML_Score",
    color="Income_Group",
    hover_name="Country_Name",
    size="GDP",
    log_x=True,
    title=f"GDP per capita vs AML Score ({YEAR})"
)


guardar(fig, "03_gdp_vs_aml")

# =====================================================
# 4 CPI vs AML
# =====================================================

if {
    "CPI_Score",
    "AML_Score"
}.issubset(df_year.columns):

    fig = px.scatter(
        df_year,
        x="CPI_Score",
        y="AML_Score",
        color="Region_Name"
        if "Region_Name" in df_year.columns
        else None,
        hover_name="Country_Name",
        title="Corrupción vs AML"
    )

    guardar(fig, "04_corrupcion")

# =====================================================
# 5 AML POR INGRESOS
# =====================================================

if {
    "Income_Group",
    "AML_Score"
}.issubset(df_year.columns):

    fig = px.box(
        df_year,
        x="Income_Group",
        y="AML_Score",
        color="Income_Group",
        title="AML por Income Group"
    )

    guardar(fig, "05_income")

# =====================================================
# 6 AML POR REGIÓN
# =====================================================

if {
    "Region_Name",
    "AML_Score"
}.issubset(df_year.columns):

    fig = px.violin(
        df_year,
        x="Region_Name",
        y="AML_Score",
        box=True,
        title="AML por región"
    )

    guardar(fig, "06_region")

# =====================================================
# 7 EVOLUCIÓN TEMPORAL
# =====================================================

if {
    "Year",
    "Region_Name",
    "AML_Score"
}.issubset(df.columns):

    trend = (
        df.groupby(
            ["Year", "Region_Name"]
        )["AML_Score"]
        .mean()
        .reset_index()
    )

    fig = px.line(
        trend,
        x="Year",
        y="AML_Score",
        color="Region_Name",
        markers=True,
        title="Evolución temporal AML"
    )

    guardar(fig, "07_evolucion")

# =====================================================
# 8 MATRIZ CORRELACIÓN
# =====================================================

corr_vars = [
    "AML_Score",
    "CPI_Score",
    "GDP_per_capita",
    "GDP",
    "Internet_Usage_Pct",
    "Life_Expectancy",
    "Unemployment_Pct"
]

# eliminar columnas completamente vacías
corr_vars = [
    col for col in corr_vars
    if col in df_year.columns
    and df_year[col].notna().sum() > 0
]

corr = df_year[corr_vars].corr()

fig = px.imshow(
    corr.round(2),
    text_auto=True,
    color_continuous_scale="RdBu_r",
    zmin=-1,
    zmax=1,
    width=900,
    height=800,
    title="Matriz de correlaciones"
)

guardar(fig, "08_correlaciones")

print(df_year["Life_Expectancy"].describe())

print("\nValores nulos:")
print(df_year["Life_Expectancy"].isna().sum())

print("\nValores únicos:")
print(df_year["Life_Expectancy"].nunique())

# =====================================================
# 9 PCA + KMEANS
# =====================================================

cluster_vars = [
    c
    for c in [
        "AML_Score",
        "CPI_Score",
        "GDP_per_capita",
        "Internet_Usage_Pct",
        "Life_Expectancy"
    ]
    if c in df.columns
]

if len(cluster_vars) >= 3:

    data = df[cluster_vars].copy()

    data = data.fillna(
        data.median()
    )

    X = StandardScaler().fit_transform(data)

    kmeans = KMeans(
        n_clusters=4,
        random_state=42,
        n_init=10
    )

    clusters = kmeans.fit_predict(X)

    pca = PCA(
        n_components=2
    )

    pca_values = pca.fit_transform(X)

    plot_df = pd.DataFrame({
        "PCA1": pca_values[:,0],
        "PCA2": pca_values[:,1],
        "Cluster": clusters.astype(str)
    })

    fig = px.scatter(
        plot_df,
        x="PCA1",
        y="PCA2",
        color="Cluster",
        title="Clusters PCA + KMeans"
    )

    guardar(fig, "09_clusters")

# =====================================================
# 10 AML vs Corrupción
# =====================================================

import plotly.express as px

fig = px.scatter(
    df_year,
    x="CPI_Score",
    y="AML_Score",
    color="Region_Name",
    hover_name="Country_Name",
    trendline="ols",
    title="Relación entre corrupción y riesgo AML"
)

fig.update_layout(
    xaxis_title="Índice de Percepción de la Corrupción (CPI)",
    yaxis_title="AML Score",
    width=1000,
    height=700
)

guardar(fig, "10_corrupcion_vs_aml")

# =====================================================
# 11 AML vs PIB per cápita
# =====================================================

df_gdp = df[
    (df["Year"] == 2018)
].dropna(
    subset=[
        "GDP_per_capita",
        "AML_Score"
    ]
)

fig = px.scatter(
    df_gdp,
    x="GDP_per_capita",
    y="AML_Score",
    color="Income_Group",
    hover_name="Country_Name",
    trendline="ols",
    log_x=True,
    title="PIB per cápita frente al riesgo AML"
)

fig.update_layout(
    width=1000,
    height=700
)

guardar(fig, "11_gdp_vs_aml")

# =====================================================
# 12 AML por región
# =====================================================

fig = px.box(
    df_year,
    x="Region_Name",
    y="AML_Score",
    color="Region_Name",
    title="Distribución del AML Score por región"
)

fig.update_layout(
    width=1000,
    height=700,
    xaxis_title="Región",
    yaxis_title="AML Score"
)

guardar(fig, "12_aml_por_region")

# =====================================================
# 13 Clustering PCA
# =====================================================

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import pandas as pd
import plotly.express as px

cluster_vars = [
    "AML_Score",
    "CPI_Score",
    "GDP_per_capita",
    "Internet_Usage_Pct",
    "Unemployment_Pct",
    "Population_Growth",
    "Birth_Rate",
    "Death_Rate"
]

cluster_vars = [c for c in cluster_vars if c in df_year.columns]

data = df_year[cluster_vars].copy()

for col in data.columns:
    data[col] = pd.to_numeric(data[col], errors="coerce")

data = data.dropna(axis=1, how="all")
data = data.loc[:, data.nunique(dropna=True) > 1]
data = data.fillna(data.median(numeric_only=True))
data = data.dropna()

print("Variables usadas en clustering:")
print(data.columns.tolist())

X = StandardScaler().fit_transform(data)

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X)

coords = PCA(n_components=2).fit_transform(X)

plot_df = df_year.loc[data.index, ["Country_Name", "Region_Name", "Income_Group"]].copy()

plot_df["PCA1"] = coords[:, 0]
plot_df["PCA2"] = coords[:, 1]
plot_df["Cluster"] = clusters.astype(str)

fig = px.scatter(
    plot_df,
    x="PCA1",
    y="PCA2",
    color="Cluster",
    symbol="Region_Name",
    hover_name="Country_Name",
    hover_data=["Region_Name", "Income_Group"],
    title="Agrupación de países mediante PCA y K-Means"
)

fig.update_layout(
    width=1000,
    height=700,
    xaxis_title="Componente principal 1",
    yaxis_title="Componente principal 2"
)

guardar(fig, "13_clusters")

# =====================================================
# 14 Ranking regional
# =====================================================

region_mean = (
    df_year
    .groupby("Region_Name")["AML_Score"]
    .mean()
    .sort_values()
    .reset_index()
)

fig = px.bar(
    region_mean,
    x="AML_Score",
    y="Region_Name",
    orientation="h",
    color="AML_Score",
    title="AML Score medio por región"
)

guardar(fig, "14_Ranking_regional")